# Jekyll

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Heng Sun （孙衡）"
title_separator          : "-"
name                     : ""
description              : ""   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://sun11999.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "sun11999.github.io"
